name: build
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  image:
    strategy:
      fail-fast: false
      matrix:
        release: [focal, jammy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: docker/setup-qemu-action@v2.0.0
      - uses: docker/setup-buildx-action@v2.0.0
      - uses: josStorer/get-current-time@v2.0.1
        id: current-time
        with:
          format: YYYYMMDD
      - uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          build-args: |
            FROM=ubuntu:${{ matrix.release }}
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            quay.io/vexxhost/openstack-runtime-${{ matrix.release }}:latest
            quay.io/vexxhost/openstack-runtime-${{ matrix.release }}:${{ steps.current-time.outputs.formattedTime }}
