name: build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  image:
    strategy:
      fail-fast: false
      matrix:
        release: [focal, jammy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker/setup-qemu-action@v2.1.0
      - uses: docker/setup-buildx-action@v2.2.1
      - uses: docker/login-action@v2
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - uses: docker/build-push-action@v3.2.0
        with:
          context: .
          cache-from: type=gha,scope=${{ matrix.release }}
          cache-to: type=gha,mode=max,scope=${{ matrix.release }}
          push: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          build-args: |
            FROM=ubuntu:${{ matrix.release }}
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            quay.io/vexxhost/openstack-runtime-${{ matrix.release }}:latest
            quay.io/vexxhost/openstack-runtime-${{ matrix.release }}:${{ github.sha }}
